[package]
name = "blaze-ssl-async"
version = "0.3.0"
edition = "2021"
description = "Legacy SSLv3 bare minimum implementation for gosredirector.ea.com async version"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/blaze-ssl"
readme = "README.md"
keywords = ["EA", "ssl", "sslv3"]
categories = ["network-programming", "parser-implementations"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
rust-crypto = "^0.2"
x509-cert = "0.1.0"
pem-rfc7468 = "0.6.0"
tokio = { version = "1", features = ["io-util", "net"] }
rsa = "0.7"

[dev-dependencies.tokio]
version = "1"
features = ["rt", "macros", "time"]
